name: "build"

on:
  push:
    branches: [ master ]
    tags: [ v* ]

jobs:
  build:
    name: "Xcode Build"
    runs-on: "macos-latest"

    steps:
      - name: "Checkout project"
        uses: actions/checkout@v2
      - name: "Setup keychain"
        run: |
          ./scripts/setup_keychain.sh
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      - name: "Build project"
        run: |
          xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME_NAME" install DSTROOT=build/root DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" | xcpretty
        env:
          PROJECT_NAME: giphy-anywhere.xcodeproj
          SCHEME_NAME: "GIPHY Anywhere"
          DEVELOPMENT_TEAM: "WPEJJ9FF9Y"
          CODE_SIGN_IDENTITY: "Developer ID Application: David Kramer (WPEJJ9FF9Y)"
      - name: "Package app"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          hdiutil create -fs HFS+ -srcfolder build/root/Applications/"$APP_NAME" -volname "$VOLUME_NAME" build/"$DISK_IMAGE_NAME"
        env:
          APP_NAME: "GIPHY Anywhere.app"
          VOLUME_NAME: "GIPHY Anywhere"
          DISK_IMAGE_NAME: "GIPHY_Anywhere.dmg"
      - name: "Notarize app"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          ./scripts/notarize.sh
        env:
          NOTARIZATION_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
          NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
      - name: "Release app"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: build/GIPHY_Anywhere.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


